version: '3.8'

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    volumes:
      - .:/code
    command: >
      sh -c "
        chmod +x scripts/init-db.sh &&
        ./scripts/init-db.sh &&
        uvicorn app.main:app --host 0.0.0.0 --reload
      "
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge