"""Initial commit

Revision ID: 1a59e01d6aab
Revises: 
Create Date: 2025-05-01 12:27:06.063443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a59e01d6aab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code', name='uq_url_mapping_short_code')
    )
    op.create_index(op.f('ix_url_mapping_id'), 'url_mapping', ['id'], unique=False)
    op.create_index(op.f('ix_url_mapping_short_code'), 'url_mapping', ['short_code'], unique=True)
    op.create_table('visit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_mapping_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('visit_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['url_mapping_id'], ['url_mapping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visit_log_id'), 'visit_log', ['id'], unique=False)
    op.create_index(op.f('ix_visit_log_url_mapping_id'), 'visit_log', ['url_mapping_id'], unique=False)
    op.create_index(op.f('ix_visit_log_visit_time'), 'visit_log', ['visit_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_log_visit_time'), table_name='visit_log')
    op.drop_index(op.f('ix_visit_log_url_mapping_id'), table_name='visit_log')
    op.drop_index(op.f('ix_visit_log_id'), table_name='visit_log')
    op.drop_table('visit_log')
    op.drop_index(op.f('ix_url_mapping_short_code'), table_name='url_mapping')
    op.drop_index(op.f('ix_url_mapping_id'), table_name='url_mapping')
    op.drop_table('url_mapping')
    # ### end Alembic commands ###
