"""Add new constraints

Revision ID: 8fe49ca2a33a
Revises: 1a59e01d6aab
Create Date: 2025-05-01 15:33:37.264105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe49ca2a33a'
down_revision: Union[str, None] = '1a59e01d6aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_url_mapping_original_short', 'url_mapping', ['original_url', 'short_code'])
    op.create_unique_constraint('uq_url_mapping_original_url', 'url_mapping', ['original_url'])
    op.create_unique_constraint(None, 'url_mapping', ['original_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_mapping', type_='unique')
    op.drop_constraint('uq_url_mapping_original_url', 'url_mapping', type_='unique')
    op.drop_constraint('uq_url_mapping_original_short', 'url_mapping', type_='unique')
    # ### end Alembic commands ###
